name: Deploy To EC2

on:
  push:
    branches:
      - main
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository에 올린 파일들을 불러오기
        uses: actions/checkout@v4                 # Github에 올린 코드들을 불러옴

      - name: JDK 17버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin                   # jdk 중에서도 temurin 브랜드를 사용한다
          java-version: 17

      - name: application.yml 파일을 만들기
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.yml

      - name: 테스트 및 빌드하기
        run: ./gradlew clean build

      - name: 빌드된 파일 이름 변경하기
        run: mv build/libs/*SNAPSHOT.jar ./project.jar

      - name: SCP로 EC2로 파일 전송하기
        uses: appleboy/scp-action@master           # SCP로 파일을 전송하는 라이브러리
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          source: "./project.jar"                  # 이 파일을 EC2로 전송
          target: "/home/ubuntu/spring-CI-CD/tobe" # EC2로 전송된 파일을 이 경로로 저장

      - name: SSH(원격 접속)로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script_stop: true
          script: |
            rm -rf /home/ubuntu/spring-CI-CD/current
            mkdir /home/ubuntu/spring-CI-CD/current
            mv /home/ubuntu/spring-CI-CD/tobe/project.jar /home/ubuntu/spring-CI-CD/current
            cd /home/ubuntu/spring-CI-CD/current
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar project.jar > ./output.log 2>&1 &
            rm -rf /home/ubuntu/spring-CI-CD/tobe